import java.util.Random;

/**
 * @author Hybrid
 * 
 * All possible planet name suffixes
 */
public class Suffix {
    private static final String[] suffixes = {
        "a",
        "ab",
        "ach",
        "adys",
        "ag",
        "ah",
        "ahl",
        "ai",
        "aia",
        "ak",
        "al",
        "alb",
        "alyx",
        "am",
        "amyr",
        "an",
        "ang",
        "ant",
        "anth",
        "ao",
        "aos",
        "aph",
        "aq",
        "ar",
        "ark",
        "arr",
        "ars",
        "arse",
        "arv",
        "ax",
        "az",
        "ea",
        "eb",
        "eed",
        "een",
        "eer",
        "ek",
        "elm",
        "elp",
        "elph",
        "en",
        "ens",
        "enth",
        "eo",
        "eol",
        "eom",
        "eon",
        "eone",
        "eph",
        "er", 
        "erg",
        "erth",
        "es",
        "esp",
        "et",
        "eum",
        "eus",
        "ev",
        "ex",
        "ez",
        "i",
        "ia",
        "iac",
        "iak",
        "ial",
        "ian",
        "ias",
        "iax",
        "iox",
        "id",
        "iem",
        "ies",
        "iex",
        "ii",
        "ik",
        "il",
        "im",
        "imph",
        "in",
        "inx",
        "io",
        "ion",
        "ior",
        "ios",
        "ioth",
        "ip",
        "iph",
        "ir",
        "is",
        "ite",
        "ith",
        "ium",
        "ius",
        "iv",
        "ix",
        "iz",
        "o",
        "oa",
        "ob",
        "obe",
        "ode",
        "of",
        "og",
        "oh",
        "ok",
        "ol",
        "olch",
        "om",
        "ome",
        "on",
        "one",
        "ons",
        "op",
        "ope",
        "ops",
        "oph",
        "or",
        "orb",
        "org",
        "orm",
        "orn",
        "os",
        "osh",
        "oss",
        "ot",
        "oth",
        "ou",
        "ov",
        "ox",
        "oz",
        "u",
        "ua",
        "ub",
        "uin",
        "uk",
        "um",
        "un",
        "une",
        "urn",
        "ury",
        "us",
        "usk",
        "uth",
        "uul",
        "ux",
        "uz",
    };

    /**
     * Gets a random suffix from the above array
     * 
     * @return The suffix
     */
    public static String getSuffix() {
        Random rand = new Random();
        String suffix = suffixes[rand.nextInt(suffixes.length)];

        return suffix;
    }

    /**
     * Gets the amount of total suffixes
     * 
     * @return The total number of possible suffixes
     */
    public static int getNumSuffixes() {
        return suffixes.length;
    }
}
